name       : drumstick
version    : 1.1.0
release    : 1
source     :
    - http://downloads.sourceforge.net/project/drumstick/1.1.0/drumstick-1.1.0.tar.bz2 : ae1d2c0d21b45d144e181b873ffbc2979a294fab31b8d71a5b0b8cad3276f38e
license    : GPL-2.0
component  : programming.library
summary    : Drumstick is a set of MIDI libraries using C++/Qt5 idioms and style.
description: |
    Drumstick is a set C++ MIDI libraries using Qt5 objects, idioms and style. It contains a C++ wrapper around the ALSA library sequencer interface; ALSA sequencer provides software support for MIDI technology on Linux. A complementary library provides classes for SMF (Standard MIDI files: .MID/.KAR), Cakewalk (.WRK), and Overture (.OVE) file formats processing. A multiplatform realtime MIDI I/O library is also provided since release 1.0.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - docbook-xml
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
