name       : drumstick
version    : 2.1.1
release    : 9
source     :
    - https://downloads.sourceforge.net/project/drumstick/2.1.1/drumstick-2.1.1.tar.bz2 : 575e095d136406dd5b350e4f66247145b12ecb889784251955b4bc77ff249f1a
license    : GPL-2.0-or-later
component  : programming.library
summary    : Drumstick is a set of MIDI libraries using C++/Qt5 idioms and style.
description: |
    Drumstick is a set C++ MIDI libraries using Qt5 objects, idioms and style. It contains a C++ wrapper around the ALSA library sequencer interface; ALSA sequencer provides software support for MIDI technology on Linux. A complementary library provides classes for SMF (Standard MIDI files: .MID/.KAR), Cakewalk (.WRK), and Overture (.OVE) file formats processing. A multiplatform realtime MIDI I/O library is also provided since release 1.0.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
    - pkgconfig(fluidsynth)
    - pkgconfig(libcgraph)
    - pkgconfig(libpulse-simple)
    - docbook-xml
    - doxygen
setup      : |
    %cmake_ninja ..
build      : |
    %ninja_build
install    : |
    %ninja_install
